server:
  port: 8888

spring:
  datasource:
    url: jdbc:mariadb://localhost:3336/test?useUnicode=yes&characterEncoding=UTF-8
    username: test
    password: test
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true

management:
  endpoints:
    web:
      cors:
        allowed-headers: "*"
        allowed-origins: "*"
      base-path: /monitor
